version: 2.1
setup: true
orbs:
    continuation: circleci/continuation@0.1.0

parameters:
    nightly:
        type: boolean
        default: false

jobs:
    # Fetch the tests to run
    fetch_tests:
        working_directory: ~/transformers
        docker:
            - image: huggingface/transformers-quality
        parallelism: 1
        steps:
            - checkout
            - run: pip uninstall -y numpy
            - run: uv pip install -U -e .
            - run: pip show numpy
            - run: python -c 'import transformers'


workflows:
    version: 2
    setup_and_quality:
        when:
            not: <<pipeline.parameters.nightly>>
        jobs:
            - fetch_tests
