name: Count 🤗 stars ⭐

on:
  push:
    branches:
      - fire

env:
  HF_HOME: /mnt/cache
  TRANSFORMERS_IS_CI: yes
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  RUN_SLOW: yes
  SIGOPT_API_TOKEN: ${{ secrets.SIGOPT_API_TOKEN }}
  TF_FORCE_GPU_ALLOW_GROWTH: true
  RUN_PT_TF_CROSS_TESTS: 1

jobs:
  send_results:
    name: Send results to webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count 🤗 stars ⭐
        shell: bash
        run: |
          python count_stars.py
