name: model jobs

on:
  workflow_call:
    inputs:
      folder_slices:
        required: true
        type: string
      machine_type:
        required: true
        type: string
      slice_id:
        required: true
        type: number

jobs:
  model_job:
    name: Model tests
    strategy:
      fail-fast: false
      matrix:
        folders: ${{ fromJson(inputs.folder_slices)[0] }}
    runs-on: yih-dar-shieh-temp-runner-for-testing-workflow-file
    steps:
      - name: Echo input and matrix info
        shell: bash
        run: |
          echo "${{ inputs.folder_slices }}"
          echo "${{ inputs.slice_id }}"
          echo "${{ matrix.folders }}"
          echo "${{ toJson(fromJson(inputs.folder_slices)[0]) }}"
