name: Self-hosted runner (scheduled)


on:
  repository_dispatch:
  schedule:
    - cron: "17 2 * * *"
  push:
    branches:
      - check-whisper-slow-tests

jobs:
  model-ci:
    name: Model CI
    uses: ./.github/workflows/self-scheduled.yml
    with:
      job: run_tests_gpu
      slack_report_channel: "#transformers-ci-daily-models"
    secrets: inherit
